AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for CloudComputing project

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3
#     MemorySize: 128

Resources:
  RegistrationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: registration/
      Handler: app.registration_lambda
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Registration:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/registration
            Method: post
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: login/
      Handler: app.login_lambda
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Login:
          Type: Api
          Properties:
            Path: /api/login
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RegistrationApi:
    Description: "API Gateway endpoint URL for Prod stage for Registration function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/registration/"
  RegistrationFunction:
    Description: "Registration Lambda Function ARN"
    Value: !GetAtt RegistrationFunction.Arn
  RegistrationFunctionIamRole:
    Description: "Implicit IAM Role created for RegistrationFunction"
    Value: !GetAtt RegistrationFunction.Arn
